config/routes.rb
Rails.application.routes.draw do
  get 'attractions/index'

  get 'attractions/show'

  # root to: 'attractions#index'

  resources :attractions

end

app/views/pages/_side_image.html.erb
<div class="side-image">
  <div class="images-wrapper"></div>
    <div class="side-image-content">
      <h1>Walt Disney World Hotels</h1>
      <p>This is very exciting.  You are about to check out the alpha version of the attractions section of WDW Hub!  Just like Walt Disney fortold about Disneyland, "Disneyland will never be completed. It will continue to grow as long as there is imagination left in the world," so too will this site. We will keep moving forward.</p>
      
<h2>   <%= link_to "Click here to see our progress.", attractions_path %>   
</h2>  </div>
</div>

app/views/pages/home.html.erb
<style>
	
.hero-section {
  background: url(<%= image_path 'background-image.jpg' %>) 50% no-repeat;
  background-size: cover;
  height: 60vh;
  text-align: center;
  display: -webkit-flex;
  display: -ms-flexbox;
  display: flex;
  -webkit-align-items: center;
      -ms-flex-align: center;
          align-items: center;
  -webkit-justify-content: center;
      -ms-flex-pack: center;
          justify-content: center;
}

.hero-section .hero-section-text {
	color: #fee;
  background: rgba(128, 128, 128, 0.7); 
}


</style>
<div class="hero-section">
  <div class="hero-section-text">
    <h2>WDW Hub Attractions Beta</h2>
    <h5>Tap <em><%= link_to "here", attractions_path, style: "color: white;text-decoration:underline;" %></em> for more <em><%= link_to "fun", attractions_path, style: "color: white;text-decoration:underline;" %></em></h5>
  </div>
</div>